### ISSUE TITLE
🚀 - Customizable Tooltips

### ISSUE THREAD

**Issue by WynieCronje** [Tinkoff/taiga-ui#1258]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

Allow css classes to be added to individual tooltips. 

This will allow color changes as well as changing the styles of tooltips as needed.

**Comment by splincode** [comment]
@waterplea if we could use a directive, would that be useful?

```html
<div class="my-custom-class" tuiTooltip>
   Please don't touch this
<div>

<div class="my-custom-class" [tuiTooltip]="template"><div>
<ng-template #template>Please don't touch this</ng-template>
```

**Comment by WynieCronje** [comment]
I have 2 solutions in my mind. One is to simply add a property `cssClass` as an input. And this will enable styling overrides on global level.

Another is to move the styling away from the `tui-hint-box` component. And into global styles. but to configure we will need to have css classes being added to `tui-hint-box` anyway.

This approach will allow for overriding default styles. then a cssClass property can switch between the desired class rules.

**Comment by loxy** [comment]
We have some similar problems, but not regarding the tooltip. This pattern (restriction) is also used in other components.

Another option would be to add some CSS variables to the styles like:

```CSS
:host {
   --tui-component-color: var(--tui-text-03);
   --tui-component-bg: transparent;

    .transition(color);
    position: relative;
    display: inline-block;
    width: 1.5rem;
    height: 1.5rem;
    vertical-align: middle;
    font-size: 0;
    line-height: 0;
    cursor: pointer;
    color: var(--tui-component-color);
    background: var(--tui-component-bg);
    ...
}
```

Then you can apply something like:

```CSS
.my-namespace tui-tooltip {
  --tui-component-color: var(--my-color-var);
  --tui-component-bg: pink;
}

tui-tooltip.special {
  --tui-component-color: var(--my-other-color-var);
  --tui-component-bg: yellow;
}
````
