### ISSUE TITLE
🐞 - `Stackblitz` css-varibles (bound on `:host`) don't work 

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#1497]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

Open stackblitz https://taiga-ui.dev/components/slider#sizes

## InputColor case
1. Open stackblitz https://taiga-ui.dev/components/color-picker#input
2. No left padding for input
3. `tui-primitive-textfield` doesn't have
```css
element.style {
    --border-start: 1.75rem;
    --border-end: 0rem;
}
```

## Slider case
1. Open stackblitz https://taiga-ui.dev/components/slider#sizes
2. `<input type="range" />` doesn't have
```css
element.style {
    --tui-slider-track-color: var(--tui-base-03);
    --tui-slider-fill-percentage: 40%;
    --tui-slider-segment-width: 100%;
}
```

### Angular version

any

### Taiga UI version

2.36.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android
